2023-06-07 18:10:21,540 ERROR Internal Server Error: /posts/index/ C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\utils\log.py (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name."), <traceback object at 0x0000020607300480>)
Traceback (most recent call last):
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\NewsPaper\news\views.py", line 23, in get
    return HttpResponse(render(request, 'index.html', context))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.
2023-06-07 18:10:21,561 ERROR "GET /posts/index/ HTTP/1.1" 500 133673 C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-06-07 21:41:26,623 ERROR Internal Server Error: /posts/index/ C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\utils\log.py (<class 'NameError'>, NameError("name 'pk' is not defined"), <traceback object at 0x000001C5C492BD80>)
Traceback (most recent call last):
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\NewsPaper\news\views.py", line 39, in post
    return HttpResponseRedirect(reverse('index', args=[pk]))
                                                       ^^
NameError: name 'pk' is not defined
2023-06-07 21:41:26,628 ERROR "POST /posts/index/ HTTP/1.1" 500 80034 C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-06-07 21:43:04,266 ERROR Internal Server Error: /posts/index/ C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\utils\log.py (<class 'NameError'>, NameError("name 'context' is not defined"), <traceback object at 0x00000237F8D3AD40>)
Traceback (most recent call last):
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\NewsPaper\news\views.py", line 40, in post
    return HttpResponse(render(request, 'index.html', context))
                                                      ^^^^^^^
NameError: name 'context' is not defined
2023-06-07 21:43:04,271 ERROR "POST /posts/index/ HTTP/1.1" 500 80171 C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\core\servers\basehttp.py None
2023-06-07 21:48:41,525 ERROR Internal Server Error: /posts/index/ C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\utils\log.py (<class 'NameError'>, NameError("name 'context' is not defined"), <traceback object at 0x000002157EFB0D40>)
Traceback (most recent call last):
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oleg\PycharmProjects\News_Portal\NewsPaper\news\views.py", line 40, in post
    HttpResponse(render(request, 'index.html', context))
                                               ^^^^^^^
NameError: name 'context' is not defined
2023-06-07 21:48:41,529 ERROR "POST /posts/index/ HTTP/1.1" 500 80158 C:\Users\Oleg\PycharmProjects\News_Portal\venv\Lib\site-packages\django\core\servers\basehttp.py None
